import { AcmeHotel } from "./AcmeService";

export const acmeHotelsMock: AcmeHotel[] = [
  {
    Id: "a1b2",
    DestinationId: 1234,
    Name: "Grand Palace Hotel",
    Latitude: 35.6895,
    Longitude: 139.6917,
    Address: "1-1-1 Chiyoda, Tokyo",
    City: "Tokyo",
    Country: "JP",
    PostalCode: "100-0001",
    Description: "A luxurious hotel located in the heart of Tokyo.",
    Facilities: [
      " Pool ",
      " WiFi ",
      " BusinessCenter ",
      " DryCleaning ",
      " Breakfast ",
    ],
  },
  {
    Id: "c3d4",
    DestinationId: 5678,
    Name: "Ocean View Resort",
    Latitude: null,
    Longitude: null,
    Address: "123 Beach Road, Sydney",
    City: "Sydney",
    Country: "AU",
    PostalCode: "2000",
    Description: "A beautiful resort with stunning ocean views.",
    Facilities: ["Pool", "WiFi  ", "  Spa", " Breakfast", "Bar "],
  },
  {
    Id: "e5f6",
    DestinationId: 9101,
    Name: "Mountain Retreat",
    Latitude: "",
    Longitude: "",
    Address: "456 Mountain Road, New York",
    City: "New York",
    Country: "US",
    PostalCode: "10001",
    Description: "A serene retreat located in the mountains.",
    Facilities: ["WiFi", "Breakfast", "Hiking Trails", "Fireplace"],
  },
];

export const expectedParsedAcmeHotels = [
  {
    id: "a1b2",
    destination_id: 1234,
    name: "Grand Palace Hotel",
    location: {
      lat: 35.6895,
      lng: 139.6917,
      address: "1-1-1 Chiyoda, Tokyo",
      city: "Tokyo",
      country: "Japan",
    },
    description: "A luxurious hotel located in the heart of Tokyo.",
    amenities: ["pool", "wifi", "business center", "dry cleaning", "breakfast"],
    images: {
      rooms: [],
      site: [],
      amenities: [],
    },
    booking_conditions: [],
  },
  {
    id: "c3d4",
    destination_id: 5678,
    name: "Ocean View Resort",
    location: {
      lat: null,
      lng: null,
      address: "123 Beach Road, Sydney",
      city: "Sydney",
      country: "Australia",
    },
    description: "A beautiful resort with stunning ocean views.",
    amenities: ["pool", "wifi", "spa", "breakfast", "bar"],
    images: {
      rooms: [],
      site: [],
      amenities: [],
    },
    booking_conditions: [],
  },
  {
    id: "e5f6",
    destination_id: 9101,
    name: "Mountain Retreat",
    location: {
      lat: null,
      lng: null,
      address: "456 Mountain Road, New York",
      city: "New York",
      country: "United States",
    },
    description: "A serene retreat located in the mountains.",
    amenities: ["wifi", "breakfast", "hiking trails", "fireplace"],
    images: {
      rooms: [],
      site: [],
      amenities: [],
    },
    booking_conditions: [],
  },
];
