services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_DBNAME: ${MONGODB_DBNAME}
    volumes:
      - ./mongo-init-scripts/:/docker-entrypoint-initdb.d/
  hotel-data-merge:
    image: hotel-data-merge
    restart: always
    container_name: hotel-data-merge
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_HOST: mongo
      MONGODB_PORT: 27017
      MONGODB_DBNAME: ${MONGODB_DBNAME}